name: "setup remote server for deployment"

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/base.setup.yml"
      - ".docker/compose/**"
      - "docker-compose-staging.yml"

jobs:
  send-compose-files-to-server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
      - uses: actions/checkout@v3 # Checking out the repo
      - name: Remove existing files from remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: rm -r /docker/staging/*
      - name: Pull compose files into remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "docker-compose.staging.yml,.docker/compose/*"
          target: "/docker/staging"
