name: "{{microserviceName}} build and push image to GH registry"

on:
  push:
    branches: [{{branchName}}]
    paths:
      - .docker/Dockerfile.{{dockerfile}}
      - .github/build.image.yml
      - .github/workflows/build-{{microserviceName}}-image.yml
{{triggerCondition}}

jobs:
  {{microserviceName}}-build-and-push-to-regestry:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: {{dockerfile}}
          push: true
          build-args: MICROSERVICE_NAME={{microserviceName}}
          tags: ghcr.io/edonec/mr-psychologue/{{microserviceName}}:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max
