version: "3.9"
services:
  front:
    build:
      context: ./apps/front
      dockerfile: Dockerfile.dev
    command:
      - NODE_OPTIONS='--inspect'
      - yarn
      - start
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./apps/front:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - ENV NEXT_TELEMETRY_DISABLED=1
