version: "3.9"
services:
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - main-network
  imgproxy:
    image: darthsim/imgproxy:latest
    restart: always
    environment:
      - IMGPROXY_USE_S3=true
      - IMGPROXY_S3_REGION=eu-west-3
      - STORAGE_PROVIDER=S3
      - STORAGE_PATH=edonec-boilerplate-files
      - AWS_ACCESS_KEY_ID=AKIARU2MX2BV2UWQOPVD
      - AWS_SECRET_ACCESS_KEY=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
      - IMGPROXY_BIND=:3000
      - IMGPROXY_CACHE_CONTROL_PASSTHROUGH=true
      - IMGPROXY_SET_CANONICAL_HEADER=true
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_JPEG_TRELLIS_QUANT=true
      - IMGPROXY_JPEG_OVERSHOOT_DERINGING=true
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_PATH_PREFIX=/imgproxy
      - IMGPROXY_MAX_SRC_RESOLUTION=9999
    networks:
      - main-network
  proxy-balancer:
    restart: always
    build:
      args:
        - PROXY_BALANCER_PATH=./proxy-balancer-dev.conf
      context: ../
      dockerfile: ./.docker/Dockerfile.proxy-balancer
    depends_on:
      - imgproxy
    ports:
      - 3007:80
    networks:
      - main-network
  zookeeper:
    restart: always
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - main-network

  broker:
    restart: always
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - main-network
  auth:
    image: auth
    restart: always
    command: node /app/index.js
    environment:
      - PORT=${PORT}
      - DATABASE_URI=mongodb://database:27017/auth?authSource=admin
      - ACCESS_TOKEN_SECRET_KEY=${ACCESS_TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - NUMBER_OF_AUTH_TRIALS=5
      - KAFKA_BROKERS=broker:9092
      - UPLOAD_SECRET_KEY=${UPLOAD_SECRET_KEY}
      - ROOT_USER_EMAIL=${ROOT_USER_EMAIL}
      - ROOT_USER_PASSWORD=${ROOT_USER_PASSWORD}
      - MICROSERVICE_NAME=auth
    networks:
      - main-network
    depends_on:
      - database

networks:
  main-network:
    driver: bridge
