name: "client build and push image to GH registry"

on: workflow_dispatch

jobs:
  client-build-and-push-to-preproduction-registry:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: "pre-production"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/Dockerfile.next
          push: true
          build-args: |
            MICROSERVICE_NAME=client
            HOST_URL=${{ vars.HOST_URL }}
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            NEXT_PUBLIC_FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
          tags: ghcr.io/edonec/mr-psychologue/client:head
          cache-from: type=gha
          cache-to: type=gha,mode=max
