name: "mailing build and push image to GH registry"

on:
  push:
    branches: [master]
    paths:
      - .docker/Dockerfile..docker/Dockerfile.express
      - .github/build.image.yml
      - .github/workflows/build-mailing-image.yml
      - "apps/APIs/mailing/**"
      - "packages/node/events/auth-events/**"
      - "packages/node/core-utils/**"
      - "packages/node/custom-error/**"
      - "packages/node/field-validator/**"
      - "packages/node/http-server/**"
      - "packages/node/events/mailing-events/**"
      - "packages/node/api-types/mailing-types/**"
      - "packages/node/token/**"
      - "packages/node/api-types/auth-types/**"
      - "packages/node/events/consumer/**"
      - "packages/node/events/producer/**"

jobs:
  mailing-build-and-push-to-regestry:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/Dockerfile.express
          push: true
          build-args: MICROSERVICE_NAME=mailing
          tags: ghcr.io/edonec/mr-psychologue/mailing:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max
