name: "build and deploy images to staging env on PR approve"

on:
  push:
    branches: [master]
    paths:
      - "apps/**"
      - ".docker/Dockerfile.*"
      - "packages/**"
      - "package.json"
      - "compose/head/*"

jobs:
  send-compose-files-to-server:
    runs-on: ubuntu-latest
    if: (github.event.review.state == 'approved')

    steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Operations
        uses: alinz/ssh-scp-action@master
        env:
          HELLO: ${{ secrets.PORT }}
          MESSAGE: ${{ secrets.USERNAME }}
        with:
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          # runs this on remove server
          ssh_before: |
            rm -rf /docker/staging || true

          # then uploads these 2 files
          scp: |
            compose/staging ${{ secrets.USERNAME }}@${{ secrets.STAGING_HOST }}:/docker/staging

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [send-compose-files-to-server]
    steps:
      - name: Set the value
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ env.USERNAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER}}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}
          AWS_REGION: ${{ secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          CONTAINERS_PORT: 3000
          NODE_ENV: ${{ secrets.NODE_ENV}}
          ACCESS_TOKEN_SECRET_KEY: ${{ secrets.STAGING_ACCESS_TOKEN_SECRET_KEY}}
          REFRESH_TOKEN_SECRET_KEY: ${{ secrets.STAGING_REFRESH_TOKEN_SECRET_KEY}}
          TOKEN_EXPIRES_IN: ${{ secrets.TOKEN_EXPIRES_IN}}
          REFRESH_TOKEN_EXPIRES_IN: ${{ secrets.REFRESH_TOKEN_EXPIRES_IN}}
          ROOT_USER_EMAIL: ${{ secrets.ROOT_USER_EMAIL }}
          ROOT_USER_PASSWORD: ${{ secrets.ROOT_USER_PASSWORD }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: APPTOKEN,USERNAME,DATABASE_USER,DATABASE_PASSWORD,AWS_REGION,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,CONTAINERS_PORT,NODE_ENV,ACCESS_TOKEN_SECRET_KEY,REFRESH_TOKEN_SECRET_KEY,TOKEN_EXPIRES_IN,REFRESH_TOKEN_EXPIRES_IN,ROOT_USER_PASSWORD,ROOT_USER_PASSWORD
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd /docker/staging
            rm -f .env || true
            rm -f fullchain.pem || true
            rm -f privkey.pem || true
            echo DATABASE_USER=$DATABASE_USER >> .env
            echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
            echo AWS_REGION=$AWS_REGION >> .env
            echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
            echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
            echo PORT=$CONTAINERS_PORT >> .env
            echo NODE_ENV=$NODE_ENV >> .env
            echo ACCESS_TOKEN_SECRET_KEY=$ACCESS_TOKEN_SECRET_KEY >> .env
            echo ROOT_USER_EMAIL=$ROOT_USER_EMAIL >> .env
            echo ROOT_USER_PASSWORD=$ROOT_USER_PASSWORD >> .env
            echo REFRESH_TOKEN_SECRET_KEY=$REFRESH_TOKEN_SECRET_KEY >> .env
            echo TOKEN_EXPIRES_IN=$TOKEN_EXPIRES_IN >> .env
            echo REFRESH_TOKEN_EXPIRES_IN=$REFRESH_TOKEN_EXPIRES_IN >> .env
            cp ../fullchain.pem .
            cp ../privkey.pem .
            docker-compose up -d --remove-orphans

  proxy-balancer-build-and-publish-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: proxy-balancer # Provide only Docker image name
          dockerfile: .docker/Dockerfile.proxy-balancer
          image-tag: staging
  proxy-balancer-deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [deploy-to-staging, proxy-balancer-build-and-publish-staging]
    steps:
      - name: Set the value
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ env.USERNAME }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: APPTOKEN,USERNAME
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd /docker/staging
            docker pull ghcr.io/edonec/boilerplate/proxy-balancer:staging
            docker-compose up --no-deps --build --force-recreate -d proxy-balancer

  auth-build-and-publish-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: auth # Provide only Docker image name
          dockerfile: .docker/Dockerfile.auth
          image-tag: staging
  auth-deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [deploy-to-staging, proxy-balancer-build-and-publish-staging, auth-build-and-publish-staging]
    steps:
      - name: Set the value
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ env.USERNAME }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: APPTOKEN,USERNAME
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd /docker/staging
            docker pull ghcr.io/edonec/boilerplate/auth:staging
            docker-compose up --no-deps --build --force-recreate -d auth

  client-build-and-publish-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: client # Provide only Docker image name
          dockerfile: .docker/Dockerfile.client
          image-tag: staging
  client-deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [deploy-to-staging, proxy-balancer-build-and-publish-staging, auth-build-and-publish-staging, client-build-and-publish-staging]
    steps:
      - name: Set the value
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ env.USERNAME }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: APPTOKEN,USERNAME
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd /docker/staging
            docker pull ghcr.io/edonec/boilerplate/client:staging
            docker-compose up --no-deps --build --force-recreate -d client

  dashboard-build-and-publish-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: dashboard # Provide only Docker image name
          dockerfile: .docker/Dockerfile.dashboard
          image-tag: staging
  dashboard-deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [deploy-to-staging, proxy-balancer-build-and-publish-staging, auth-build-and-publish-staging, client-build-and-publish-staging, dashboard-build-and-publish-staging]
    steps:
      - name: Set the value
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ env.USERNAME }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: APPTOKEN,USERNAME
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd /docker/staging
            docker pull ghcr.io/edonec/boilerplate/dashboard:staging
            docker-compose up --no-deps --build --force-recreate -d dashboard


  end-to-end-test-staging-deployment:
    runs-on: ubuntu-latest
    needs: [proxy-balancer-deploy-to-staging, auth-deploy-to-staging, client-deploy-to-staging, dashboard-deploy-to-staging]
    steps:
      - name: lets see
        run: |
          echo "Hello world"
