name: "deploy app to staging"

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/staging.deploy.yml"
      - ".github/base.deploy.yml"
      - "compose/staging/*"

jobs:
  send-compose-files-to-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Operations
        uses: alinz/ssh-scp-action@master
        env:
          HELLO: ${{ secrets.PORT }}
          MESSAGE: ${{ secrets.USERNAME }}
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          # runs this on remove server
          ssh_before: |
            rm -rf /docker/staging || true

          # then uploads these 2 files
          scp: |
            compose/staging ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/docker/staging

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [send-compose-files-to-server]
    steps:
      - name: Set the value
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ env.USERNAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          envs: APPTOKEN,USERNAME
          script: |
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
            cd /docker/staging
            echo PROT=$APPTOKEN >> .env
            echo NAME=$USERNAME >> .env
            docker-compose up --build --force-recreate -d --remove-orphans
